@startuml

interface Catalog
interface Inventory



class CatalogCLI implements Catalog
class InMemoryInventory implements Inventory
ShoppingCartService --> Catalog
note on link: reference  Catalog
ShoppingCartService --> Inventory
note on link: reference  Inventory

class ShoppingCartService {
    - shoppingCartProductList: Product[]
    +add(product: Product);
    +showProductsInShoppingCartList();
}

class CatalogCLI {
    +selectProduct();
}

class InMemoryInventory {
    +get(productId: string);
}

@enduml